name: Update Repositories List

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get latest release tag
        id: get-release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/vafeenLab/update-repos-kotlin/releases/latest | jq -r '.tag_name')
          echo "Latest tag: $LATEST_TAG"
          echo "tag_name=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Checkout update-repos-kotlin
        uses: actions/checkout@v3
        with:
          repository: 'vafeenLabs/update-repos-kotlin'
          ref: ${{ steps.get-release.outputs.tag_name }}
          path: 'update-repos-kotlin'

      - name: Build the project with Gradle
        working-directory: ./update-repos-kotlin
        run: |
          # Проверяем наличие gradlew
          if [ ! -f "./gradlew" ]; then
            echo "::error::gradlew not found!"
            exit 1
          fi
          
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: Find and copy JAR file
        run: |
          JAR_PATH=$(find update-repos-kotlin/build/libs -name "*.jar" ! -name "*-sources.jar" ! -name "*-javadoc.jar" | head -n 1)
          if [[ -z "$JAR_PATH" ]]; then
            echo "::error::No JAR file found in build/libs!"
            exit 1
          fi
          cp "$JAR_PATH" ./update-repos.jar
          echo "JAR copied to: $(pwd)/update-repos.jar"

      - name: Run the updater
        run: |
          java -jar ./update-repos.jar

      - name: Check for changes
        run: |
          if git diff --quiet; 
            then echo "No changes detected. Skipping commit and push."
          else 
            git config --local user.name "GitHub Actions Bot"
            git config --local user.email "actions@github.com"
            git add profile/README.md
            git commit -m "Update repository list with header"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
