name: Update Repositories List

on:
  schedule:
    - cron: "0 0 * * *" # Выполнять каждый день в полночь
  workflow_dispatch: # Позволяет запускать вручную

permissions:
  contents: write # Разрешение на запись в репозиторий

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get latest release from vafeenLabs/update-repos-kotlin
        id: get-release
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'vafeenLabs',
              repo: 'update-repos-kotlin'
            });
            return response.data.tag_name;

      - name: Checkout update-repos-kotlin
        uses: actions/checkout@v3
        with:
          repository: 'vafeenLabs/update-repos-kotlin'
          ref: ${{ steps.get-release.outputs.result }}
          path: 'update-repos-kotlin'

      - name: Build the project
        working-directory: ./update-repos-kotlin
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Copy JAR file
        run: |
          JAR_PATH=$(find update-repos-kotlin/build/libs -name "*.jar" ! -name "*-sources.jar" | head -n 1)
          cp "$JAR_PATH" ./update-repos.jar
          echo "JAR copied to: $(pwd)/update-repos.jar"

      - name: Run the updater
        run: |
          java -jar ./update-repos.jar

      - name: Check for changes
        run: |
          if git diff --quiet; 
            then echo "No changes detected. Skipping commit and push."
          else 
            git config --local user.name "GitHub Actions Bot"
            git config --local user.email "actions@github.com"
            git add profile/README.md
            git commit -m "Update repository list with header"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}