name: Update Repositories List

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get latest release tag
        id: get-release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/vafeenLabs/update-repos-kotlin/releases/latest | jq -r '.tag_name')
          echo "Latest tag: $LATEST_TAG"
          echo "tag_name=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Download release JAR
        uses: actions/download-artifact@v3
        with:
          repository: vafeenLabs/update-repos-kotlin
          name: update-repos
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and rename JAR
        run: |
          JAR_FILE=$(find . -name "*.jar" | head -n 1)
          if [[ -z "$JAR_FILE" ]]; then
            echo "::error::JAR file not found!"
            exit 1
          fi
          mv "$JAR_FILE" update-repos.jar
          echo "Using JAR file: update-repos.jar"

      - name: Run the updater
        run: |
          java -jar ./update-repos.jar

      - name: Check for changes
        run: |
          if git diff --quiet; 
            then echo "No changes detected. Skipping commit and push."
          else 
            git config --local user.name "GitHub Actions Bot"
            git config --local user.email "actions@github.com"
            git add profile/README.md
            git commit -m "Update repository list"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}